project/my_pjt/06pjt/mypjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

project/my_pjt/06pjt/mypjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

project/my_pjt/06pjt/mypjt/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

project/my_pjt/06pjt/mypjt/accounts/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import get_user_model


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            # next가 있는 경우
            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            
            return redirect('movies:index')

    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
@require_http_methods(["POST"])
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

@login_required
@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
@require_http_methods(["POST"])
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

@login_required
@require_http_methods(["GET", "POST"])
def change_password(request, user_pk):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

@require_http_methods(["GET"])
def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)

@login_required
@require_http_methods(["POST"])
def follow(request, user_pk):
    User = get_user_model()
    you = User.objects.get(pk=user_pk)

    if request.user != you:
        if request.user in you.followers.all():
            you.followers.remove(request.user)
        else:
            you.followers.add(request.user)
        return redirect('accounts:profile', you.username)

project/my_pjt/06pjt/mypjt/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
  <h1>CHANGE PASSWORD</h1>
  <hr>
  <form action="{% url "change_password" user.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="비밀번호 변경">
  </form>
{% endblock content %}

project/my_pjt/06pjt/mypjt/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>LOGIN PAGE</h1>
  <hr>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='로그인'>
  </form>
{% endblock content %}

project/my_pjt/06pjt/mypjt/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ person.username }}님의 프로필</h2>
  <hr>
  <p>팔로워 : {{ person.followers.all|length }}</p>
  <p>팔로잉 : {{ person.followings.all|length}}</p>

  {% comment %} 팔로우 버튼 {% endcomment %}
  {% if request.user != person %}
    <form action="{% url "accounts:follow" person.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <input type="submit" value='언팔로우'>
      {% else %}
        <input type="submit" value='팔로우'>
      {% endif %}
    </form>
  {% endif %}

  <hr>
  <h3>작성한 영화 목록</h3>
  <ul>
    {% for movie in person.movie_set.all %}
        <li><a href="{% url "movies:detail" movie.pk %}">{{ movie.title }}</a></li>
      {% empty %}
        <p>아직 작성한 영화가 없습니다.</p>
    {% endfor %}
  </ul>
  <hr>
  <h3>좋아요 누른 영화 목록</h3>
  <ul>
    {% for movie in person.like_movies.all %}
        <li><a href="{% url "movies:detail" movie.pk %}">{{ movie.title }}</a></li>
      {% empty %}
        <p>아직 좋아요를 누른 영화가 없습니다.</p>
    {% endfor %}
  </ul>
{% endblock content %}

project/my_pjt/06pjt/mypjt/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
  <h1>SIGNUP PAGE</h1>
  <hr>
  <form action="{% url "accounts:signup" %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
  </form>
{% endblock content %}

project/my_pjt/06pjt/mypjt/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
  <h1>USER INFO UPDATE PAGE</h1>
  <hr>
  <form action="{% url "accounts:update" %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='수정'>
  </form>
  <br>
  <form action="{% url "accounts:delete" %}" method='POST'>
    {% csrf_token %}
    <input type="submit" value='회원탈퇴'>
  </form>
{% endblock content %}